<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <EmbeddedResource Include="../../App_Data/dev-window.stationery-ui.json" LogicalName="StationeryUI.dev-window.stationery-ui.json" />
    <AssemblyMetadata Include="StationeryDeveloperStyleSource" Value="$([System.IO.Path]::GetFullPath('$(MSBuildProjectDirectory)/../../App_Data/dev-window.stationery-ui.json'))" Condition="'$(Configuration)' == 'Debug'" />
    <ProjectReference Include="../StationeryUI/StationeryUI.csproj" />
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.5.1" />
  </ItemGroup>
</Project>
