<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net8.0-windows</TargetFramework><IsPackable>false</IsPackable><EnableWindowsTargeting>true</EnableWindowsTargeting></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/StationeryUI.MonoGame/StationeryUI.MonoGame.csproj" />
    <ProjectReference Include="../../src/StationeryUI.Windows/StationeryUI.Windows.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="../../App_Data/demo.stationery-style.json" Link="App_Data/demo.stationery-style.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <EmbeddedResource Include="../../App_Data/demo.stationery-style.json" LogicalName="StationeryUI.Demo.demo.stationery-style.json" />
    <None Include="../../App_Data/demo.stationery-config.json" Link="App_Data/demo.stationery-config.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <AssemblyMetadata Include="StationeryConfigurationSource" Value="$([System.IO.Path]::GetFullPath('$(MSBuildProjectDirectory)/../../App_Data/demo.stationery-config.json'))" Condition="'$(Configuration)' == 'Debug'" />
  </ItemGroup>
</Project>
